(require 'rainbow-delimiters)
(set-face-foreground 'rainbow-delimiters-depth-1-face "#21243d")
(set-face-foreground 'rainbow-delimiters-depth-2-face "#ff7c7c")
(set-face-foreground 'rainbow-delimiters-depth-3-face "#ffd082")
(set-face-foreground 'rainbow-delimiters-depth-4-face "#88e1f2")
(set-face-foreground 'rainbow-delimiters-depth-5-face "#b590ca")
(set-face-foreground 'rainbow-delimiters-depth-6-face "#10316b")
(set-face-foreground 'rainbow-delimiters-depth-7-face "#e25822")
(set-face-foreground 'rainbow-delimiters-depth-8-face "#f0134d")
(set-face-foreground 'rainbow-delimiters-depth-9-face "#4d4646")
